version: 2.1

      orbs:
        aws-ecr: circleci/aws-ecr@6.5.0
        aws-ecs: circleci/aws-ecs@0.0.10

      workflows:
        build-and-deploy:
          jobs:
            - aws-ecr/build-and-push-image:
                account-url: AWS_ECR_ACCOUNT_URL
                repo: "${MY_APP_PREFIX}"
                region: AWS_REGION
                tag: "${CIRCLE_SHA1}"
            - aws-ecs/deploy-service-update:
                requires:
                  - aws-ecr/build-and-push-image
                family: "${MY_APP_PREFIX}-service"
                cluster-name: "${MY_APP_PREFIX}-cluster"
                container-image-name-updates: "container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}"

  update-task-definition-from-json:
    description: |
      Use the AWS CLI and this orb to create a new ECS task definition
      based upon a local JSON file.
    usage:
      version: 2.1

      orbs:
        aws-cli: circleci/aws-cli@0.1.4
        aws-ecs: circleci/aws-ecs@1.0.5

      jobs:
        update-tag:
          docker:
            - image: circleci/python:3.7.1
          steps:
            - aws-cli/install
            - aws-cli/configure:
                aws-access-key-id: "$AWS_ACCESS_KEY_ID"
                aws-region: "$AWS_REGION"
            - aws-ecs/update-task-definition-from-json:
                task-definition-json: "my-app-definition.json"
  update-service:
    description: |
      Use the AWS CLI and this orb to update an ECS service.
      (Supports both EC2 and Fargate launch types)
    usage:
      version: 2.1

      orbs:
        aws-cli: circleci/aws-cli@0.1.4
        aws-ecs: circleci/aws-ecs@0.0.10

      jobs:
        update-tag:
          docker:
            - image: circleci/python:3.7.1
          steps:
            - aws-cli/install
            - aws-cli/configure:
                aws-access-key-id: "$AWS_ACCESS_KEY_ID"
                aws-region: "$AWS_REGION"
            - aws-ecs/update-service:
                family: "${MY_APP_PREFIX}-service"
                cluster-name: "${MY_APP_PREFIX}-cluster"
                container-image-name-updates: "container=${MY_APP_PREFIX}-service,tag=stable"

      workflows:
        deploy:
          jobs:
            - update-tag

  verify-revision-deployment:
    description: Verify the deployment of an ECS revision.
    usage:
      version: 2.1

      orbs:
        aws-cli: circleci/aws-cli@0.1.4
        aws-ecs: circleci/aws-ecs@0.0.10

      jobs:
        verify-deployment:
          docker:
            - image: circleci/python:3.7.1
          steps:
            - aws-cli/install
            - aws-cli/configure:
                aws-access-key-id: "$AWS_ACCESS_KEY_ID"
                aws-region: "$AWS_REGION"
            - run:
                name: Get last task definition
                command: |
                  TASK_DEFINITION_ARN=$(aws ecs describe-task-definition \
                      --task-definition ${MY_APP_PREFIX}-service \
                      --output text \
                      --query 'taskDefinition.taskDefinitionArn')
                  echo "export TASK_DEFINITION_ARN='${TASK_DEFINITION_ARN}'" >> $BASH_ENV
            - aws-ecs/verify-revision-is-deployed:
                family: "${MY_APP_PREFIX}-service"
                cluster-name: "${MY_APP_PREFIX}-cluster"
                task-definition-arn: "${TASK_DEFINITION_ARN}"

      workflows:
        test-workflow:
          jobs:
            - verify-deployment
