
      #- add_ssh_keys:
          #fingerprints:
           # - "6e:0b:e1:81:d6:31:89:19:1f:3b:d8:15:15:b8:a5:fd"

version: 2.1
description: Commands over SSH

commands:
  exec:
    description: Commands over SSH without host context
    parameters:
      fingerprint:
        type: string
      host:
        type: string
      user:
        type: string
        default: "root"
      script:
        type: string
        default: "pwd"
      no_output_timeout:
        type: string
        default: 10m
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6e:0b:e1:81:d6:31:89:19:1f:3b:d8:15:15:b8:a5:fd"
      - run:
          name: Commands over SSH without host context
          no_output_timeout: << parameters.no_output_timeout >>
          command: |
            ssh -o StrictHostKeyChecking=no -T << parameters.user >>@<< parameters.host >> \<< 'EOSSH'
              << parameters.script >>
            EOSSH








